---
version: "3.7"

services:
  app:
    build: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "443:443/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - config:/etc/wireguard/

volumes:
  config:
