---
version: "3.7"

services:
  app:
    build: wireguard
    restart: unless_stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "443:443"
    volumes:
      - config:/etc/wireguard/

volumes:
  config:
